#! /usr/bin/env python

from __future__ import print_function
import yoda, random

h = yoda.Histo2D(5,0.,10., 5,0.,10., "/foo")
for _ in range(100):
    h.fill(random.gauss(5, 3), random.gauss(5, 2))
print(h)
print(h.bins)

yoda.write([h], "h2d.yoda")
aos = yoda.read("h2d.yoda")
for _, ao in aos.items():
    print(ao)

yoda.write([h], "h2d.dat")
# aos = yoda.read("h2d.dat")
# for _, ao in aos.iteritems():
#     print ao

s = yoda.mkScatter(h)
s = h.mkScatter()
s2 = s.mkScatter()
