#! /usr/bin/env python

import yoda

s = yoda.Scatter2D("/foo")
s.addPoint(3, 3, 0.1, 0.2)
s.addPoint(10, 5, (0.1,0.2), [0.5,0.5])
print s

yoda.write([s], "s2d.yoda")
aos = yoda.read("s2d.yoda")
for _, ao in aos.iteritems():
    print ao
