#! /usr/bin/env python

import yoda, random

p1 = yoda.Profile1D(20, 0.0, 100.0, path="/foo", title="MyTitle")

linspace = yoda.linspace(20, 0.0, 100.0)
p2 = yoda.Profile1D(linspace, path="/bar", title="Linearly spaced histo")

logspace = yoda.logspace(20, 1.0, 64)
p3 = yoda.Profile1D(logspace, path="/baz", title="Log-spaced histo")


NUM_SAMPLES = 1000
for i in range(NUM_SAMPLES):
    exp = - (i-NUM_SAMPLES/2)**2 / float(NUM_SAMPLES/4)
    val = 2.718 ** exp
    p1.fill(val, random.gauss(5, 3));
    p2.fill(val, random.gauss(5, 3));
    p3.fill(val, random.gauss(5, 3));
print p1
print p2
print p3


yoda.write([p1,p2,p3], "p1d.yoda")
aos = yoda.read("p1d.yoda")
for _, ao in aos.iteritems():
    print ao

yoda.writeFLAT([p1,p2,p3], "p1d.dat")
aos = yoda.read("p1d.dat")
for _, ao in aos.iteritems():
    print ao

s = yoda.mkScatter(p1)
s = p1.mkScatter()
s2 = s.mkScatter()
